Install [WIP]

diff --git a/backend/install b/backend/install
--- a/backend/install
+++ b/backend/install
@@ -1,34 +1,67 @@
 #!/bin/bash
 
-#TO-DO assume this is not installed in embedded system (ie user git clones or downloads source and installer needs to start from there
+YELLOW='\033[1;33m'
+RED='\033[0;31m'
+NC='\033[0m'
+
+if [ "$EUID" -ne 0 ]
+  then echo "${RED}Install script must be run by root or with sudo${NC}"
+  exit
+fi
+
+echo -e "${YELLOW} ---> Installing required system packages${NC}"
 
 apt-get update
 apt-get -y upgrade
 
-DEBIAN_FRONTEND=noninteractive apt-get -y install htop iputils-ping zip unzip whois traceroute vim openssh-server curl git libssl-dev libxslt-dev libxml2-dev imagemagick libmagickwand-dev libreadline-dev zlib1g-dev libsqlite3-dev libpq-dev build-essential libxml2-dev build-essential libxslt1-dev zlib1g-dev python-dev vim git sudo
+DEBIAN_FRONTEND=noninteractive apt-get -y -q install htop iputils-ping zip unzip whois traceroute vim openssh-server curl git libssl-dev libxslt-dev libxml2-dev imagemagick libmagickwand-dev libreadline-dev zlib1g-dev libsqlite3-dev libpq-dev build-essential libxml2-dev build-essential libxslt1-dev zlib1g-dev python-dev vim git sudo iptables network-manager
 
-DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
 APOLLO_DIR=/opt/apolloapi
 
-sudo adduser --disabled-password --gecos "" futurebit
+echo -e "${YELLOW} ---> Adding futurebit user${NC}"
 
-sudo mkdir -p $APOLLO_DIR
+adduser -q --disabled-password --gecos "" futurebit
 
-git clone --recurse-submodules -j8 https://github.com/jstefanop/apolloapi.git $APOLLO_DIR
+grep -qxF 'futurebit  ALL=(ALL) NOPASSWD:ALL' /etc/sudoers || echo 'futurebit  ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
 
-sudo chown -R futurebit $APOLLO_DIR  #TO-DO have root run script and permissions
+echo -e "${YELLOW} ---> Cloning Apollo app${NC}"
+
+mkdir -p $APOLLO_DIR
+
+if [ "$1" = "dev" ]; then
+	echo -e "${YELLOW} ---> Using DEV branch"
+	git clone --single-branch --branch dev-BTC https://github.com/CryptofyCH/apolloapi.git $APOLLO_DIR
+	rm -rf $APOLLO_DIR/apolloui
+	git clone --single-branch --branch dev-BTC https://github.com/CryptofyCH/apolloui.git $APOLLO_DIR/apolloui
+else
+	git clone --recurse-submodules -j8 https://github.com/jstefanop/apolloapi.git $APOLLO_DIR
+fi
+
+chown -R futurebit $APOLLO_DIR
+
+echo -e "${YELLOW} ---> Installing firewall${NC}"
+
+RC_LOCAL=/etc/rc.local
+
+if [ ! -f "$RC_LOCAL" ]; then
+	touch RC_LOCAL
+fi
+
+grep -q -F "$APOLLO_DIR/scripts/firewall" $RC_LOCAL || sed -i "\$i \/opt\/apolloapi\/scripts\/firewall" $RC_LOCAL
+
+echo -e "${YELLOW} ---> Becoming futurebit user${NC}"
 
 cd $APOLLO_DIR
 
-### NVM ###                   TO-DO setup so UI runs on stock NVM install (ie sudo apt install nvm)
-echo -e "Installing nvm..."
+echo -e "${YELLOW} ---> Installing NVM${NC}"
 
 if [ -e ~/.nvm/nvm.sh ]
 then
 	echo "nvm installed yet"
 else
 	echo "Installing nvm"
-	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
+	mkdir /usr/local/nvm
+	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | NVM_DIR=/usr/local/nvm bash
 fi
 
 . ~/.nvm/nvm.sh
@@ -36,47 +69,39 @@ fi
 nvm install 14.16.1
 nvm alias default 14.16.1
 
-### SYSTEMD ###
-echo -e "Installing systemd..."
-
-sudo cp backend/apollo-ui.service /etc/systemd/system/
-sudo cp backend/apollo-miner.service /etc/systemd/system/
-sudo cp backend/node.service /etc/systemd/system/
-
-sudo systemctl daemon-reload
-
-sudo systemctl enable apollo-ui
-sudo systemctl enable apollo-miner
-sudo systemctl enable node
-
-#TO-DO Use perminant iptable to redirect ports instead of this script?
-
-grep -q -F "$APOLLO_DIR/scripts/firewall" /etc/rc.local || sudo sed -i "\$i \/opt\/apolloapi\/scripts\/firewall" /etc/rc.local
-
-### SYSTEM ###
-echo "Configuring miner system..."
-
-#TO-DO move correct miner binary based on system being installed on
-
 ### API ###
-echo "Building UI (could take few minutes)..."
-
-# TO-DO we should get git submodules for UI but git should be public for this otherwise you have to pack api+ui together
-# git submodule update --init --recursive
+echo -e "${YELLOW} ---> Installing API modules${NC}"
 
 npm -g i yarn
+
+yarn
+
+echo -e "${YELLOW} ---> Installing UI modules${NC}"
 
 cd $APOLLO_DIR/apolloui
 
 yarn
 
+echo -e "${YELLOW} ---> Building UI (could take few minutes)${NC}"
+
 yarn build
 
-### START ###
-echo "Starting Apollo App..."
+echo -e "${YELLOW} ---> Starting firewall${NC}"
 
-sudo bash $APOLLO_DIR/backend/firewall
+bash $APOLLO_DIR/backend/firewall
 
-sudo systemctl start apollo-ui
+### SYSTEMD ###
+echo -e "${YELLOW} ---> Installing systemd files${NC}"
 
-echo -e "Installation complete"
+cp $APOLLO_DIR/backend/apollo-ui.service /etc/systemd/system/
+cp $APOLLO_DIR/backend/apollo-miner.service /etc/systemd/system/
+cp $APOLLO_DIR/backend/node.service /etc/systemd/system/
+
+systemctl daemon-reload
+
+systemctl enable apollo-ui
+systemctl enable apollo-miner
+systemctl enable node
+systemctl start apollo-ui
+
+echo -e "${YELLOW} Installation complete${NC}"
